import type { Metadata } from "next";
import "./globals.css";
import {Plus_Jakarta_Sans} from 'next/font/google';
import Navbar from "@/components/layouts/Navbar";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300","400", "500","600","700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
